# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-100896642-1'

menu:
- {name: 'home', url: '/'}
- {name: 'research', url: '/research'}
- {name: 'teaching', url: '/teaching'}
- {name: 'resources', url: '/resources'}
#- {name: 'people', url: '/people'}
- {name: 'blog', url: '/blog'}
- {name: 'cv', url: '/cv'}

people:
# - {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
# - {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
# - {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

teaching:
# - {name: 'Vector Calculus', url: 'vector-calculus'}
# - {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
# - {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/aadityadar'}
- {icon: 'twitter', link: 'https://twitter.com/aadityadar'}
- {icon: 'orcid', link: 'https://orcid.org/0000-0002-6745-6358'}
# - {icon: 'link', link: 'https://publons.com/researcher/2959754/aaditya-dar/'}

contacts:
- {name: 'Aaditya Dar', title: 'Assistant Professor', department: 'Economics', institution: 'Indian School of Business', institution_address: 'Hyderabad, Telangana – 500111', phone: '(000) 000-0000', email: 'aadityadar@gmail.com', office: 'Academic Center 8, Room 8117', image: 'assets/img/contact.jpg'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
